version: '3'

services:
  web:        # web 이라고 명명된 container
    build: .  # 현재 디렉토리 파일을 이용한다는 의미
    # Gunicorn 사용 전
    # command: python manage.py runserver 0.0.0.0:8000  # 가상 환경 내에서 명령 수행
    # Gunicorn 사용
    command: gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/  # 현재 폴더를 /usr/src/app/ 가상 폴더와 연결
    ports:
      - 8000:8000  # 로컬 8000과 가상 환경의 8000이 함께 open 되도록 설정
    env_file:
      - ./.env.dev # 웹 사이트의 에러 메시지 표시 dev(개발) 모드
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=do_it_django_db_user
      - POSTGRES_PASSWORD=do_it_django_db_password
      - POSTGRES_DB=do_it_django_dev
volumes:
  postgres_data:







